# Generated by Django 4.1.4 on 2023-01-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('benefits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Active_Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('latin_name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=300)),
                ('bg_image', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('description', models.TextField(max_length=50000)),
                ('benefits', models.ManyToManyField(related_name='active_ingredients', to='benefits.benefit')),
            ],
        ),
    ]
