# Generated by Django 4.1.4 on 2022-12-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediums', '0001_initial'),
        ('active_ingredients', '0002_alter_active_ingredient_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='active_ingredient',
            name='mediums',
            field=models.ManyToManyField(related_name='active_ingredients', to='mediums.medium'),
        ),
    ]
