# Generated by Django 4.1.4 on 2022-12-07 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('active_ingredients', '0002_alter_active_ingredient_description'),
        ('recipes', '0003_alter_recipe_steps'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='recipe',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='active_ingredient',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='active_ingredients.active_ingredient'),
        ),
    ]
