# Generated by Django 4.1.4 on 2022-12-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0001_initial'),
        ('remedies', '0002_remedy_common_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='remedy',
            name='benefits',
            field=models.ManyToManyField(related_name='remedies', to='benefits.benefit'),
        ),
    ]
