# Generated by Django 4.1.4 on 2022-12-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('active_ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=1000)),
                ('other_ingredients', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=1000)),
                ('active_ingredients', models.ManyToManyField(related_name='active_ingredients', to='active_ingredients.active_ingredient')),
            ],
        ),
    ]
