# Generated by Django 4.1.4 on 2022-12-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mediums', '0001_initial'),
        ('active_ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=1000)),
                ('inventory', models.TextField(max_length=1000)),
                ('steps', models.TextField(max_length=10000)),
                ('active_ingredients', models.ManyToManyField(related_name='recipes', to='active_ingredients.active_ingredient')),
                ('mediums', models.ManyToManyField(related_name='recipes', to='mediums.medium')),
            ],
        ),
    ]
