# Generated by Django 4.1.4 on 2023-01-15 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('active_ingredients', '0001_initial'),
        ('mediums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=2000)),
                ('inventory', models.TextField(max_length=2000)),
                ('steps', models.TextField(max_length=10000)),
                ('active_ingredients', models.ManyToManyField(blank=True, default=None, related_name='recipes', to='active_ingredients.active_ingredient')),
                ('mediums', models.ManyToManyField(blank=True, default=None, related_name='recipes', to='mediums.medium')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
