# Generated by Django 4.1.4 on 2022-12-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_active_ingredients_alter_recipe_mediums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
