# Generated by Django 4.1.4 on 2022-12-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_ingredients', '0003_active_ingredient_mediums'),
        ('mediums', '0001_initial'),
        ('recipes', '0003_alter_recipe_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='mediums',
            field=models.ManyToManyField(related_name='recipes', to='mediums.medium'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='active_ingredients',
            field=models.ManyToManyField(related_name='recipes', to='active_ingredients.active_ingredient'),
        ),
    ]
