# Generated by Django 4.1.4 on 2022-12-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
